### DISCUSSION TITLE
Cannot get either Powershell adapter working

### DISCUSSION THREAD

**Discussion by hansze** [PowerShell/DSC#479] [Q&A]
I have tried using both the Powershell.DSC adapter for class based PowerShell resources as well as WindowsPowerShell.Dsc classic (Binary  / File - is this supported)  resources to no avail.

The behavior I get for both is that they fail in the resource discovery phase but strangely enough differently. Both get hung up and  'never' return a config get operation. I tried both JSON and YAML input via file. 

Below my failed attempts with simple samples using the script based with resources define in the below JSON and calling

```dsc -l trace config get -p <PathToJSONFIle>```

JSON
```json
{
    "$schema":  "https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json",
    "resources":  [
        {
            "name":  "SimpleClassicFileResourceTest",
            "type":  "Microsoft.Windows/WindowsPowerShell",
            "properties":  {
                "resources":  [
                    {
                        "name":  "TestFile",
                        "type":  "PSDesiredStateConfiguration/File",
                        "properties":  {
                            "DestinationPath":  "C:\\PSTEMP\\Test.txt",
                            "type": "File",
                            "contents": "Nothing special"
                            "Ensure": "Present"
                        }
                    }
                ]

            }
        }
    ]
}
```
![image](https://github.com/PowerShell/DSC/assets/17055355/270b0f92-0203-4ce5-ac4d-744457ef55e2)
Hangs... stopped at 25min
![image](https://github.com/PowerShell/DSC/assets/17055355/95e2fa1c-e267-4335-889a-f63d3d33ba49)

I am not sure why it is even trying to enumerate all these resources as if it was doing a list all - the config is very specifically looking for an  adapter type *Microsoft.Windows/WindowsPowerShell* with fully qualified name *PSDesiredStateConfiguration/File*. As mentioned above this is implemented as binary but that should not matter... or. The behavior does not indicate that this is the issue as it never even gets back from enumerating the PowerShell.Dsc adapted resources.

Below the second adapter failed attempt. Here it can be seen at least enumerating the proper adapter type straight away but is still hangs...

YAML
```yaml $schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
- name: SimpleClassBased
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: TestEnv
      type: PSDscResources/Environment
      properties:
        Name: TestEnv
        Ensure: Present
        Value: TestValue
```

Same command as previously but ´slightly different path

dsc.exe config get -p <YAMLFilePath>

Goes for the proper adapter right away
![image](https://github.com/PowerShell/DSC/assets/17055355/372dc6a9-b8fa-44c8-80c6-69655eabecc8)

Even loads the YAML and finds the adapted resource *PSDscResources/Environment*

![image](https://github.com/PowerShell/DSC/assets/17055355/f58740c9-8a39-4641-af54-558bf005c573)

But then hangsup (just waited 3 + min here...)
![image](https://github.com/PowerShell/DSC/assets/17055355/3b183cf1-99b6-4bed-aaf8-e7754126dcb1)

Before I try to debug this stepping in code... can anyone verify that what I have attempted above should work and is intended to work this way. There were no docs that I could find showing how to leverage adapted resources. 

Version: dsc 3.0.0-preview.8
