### DISCUSSION TITLE
Implementing DSC v3 in a few Windows developer tools.

### DISCUSSION THREAD

**Discussion by denelon** [PowerShell/DSC#664] [General]
I'm aggregating a bit of the work towards WinGet Configuration and DSC v3. I've filed a few issues.

I would be super excited to get DSC v3 support in a few of our most popular products and have sold references for external folks who we would like to start adopting DSC v3. We're going to need the "zero to hero" documentation on how to build/test DSC v3 implementations, and I'd really love to make sure we have WinGet Configuration files for all the GitHub projects. We've recently updated our guidance: [How to author a WinGet Configuration file | Microsoft Learn](https://learn.microsoft.com/en-us/windows/package-manager/configuration/create#file-naming-convention)

* https://github.com/microsoft/winget-cli/issues/3767
* https://github.com/microsoft/winget-cli/issues/4103
  * User Settings
  * Admin Settings
  * Package Management
* https://github.com/microsoft/terminal/issues/15862
  * Actions
  * Schemes
  * Themes
* https://github.com/microsoft/PowerToys/issues/37276
  * Find my mouse
  * Zoomit
* https://github.com/PowerShell/PowerShell/issues/24935
  * $PROFILE
* https://github.com/microsoft/winget-create/issues/602
  * User Settings

**Comment by Gijsreyn** [comment]
Hi @denelon, thanks for opening up the discussion. Perhaps we can add the dotnet CLI to it, which I opened up in the past already: https://github.com/dotnet/sdk/issues/44325

I'm not sure if I can be of full use at the moment to do the programmatic part, so in that case, I would be very eager to write documentation on it.

**Reply by denelon** [reply]
Documentation is every bit as important as the example code! If there isn't a good "zero to hero" guide, it makes it very difficult to adopt. I believe @AmelBawa-msft will be looking at one of these along with guidance from @SteveL-MSFT next week as a hackathon project.

**Comment by denelon** [comment]
I just updated:
* https://github.com/JanDeDobbeleer/oh-my-posh/issues/4340

I'm a huge fan of oh-my-posh, and it would be awesome to have that in a WinGet configuration file as well.

**Reply by denelon** [reply]
PR in progress: 
* https://github.com/JanDeDobbeleer/oh-my-posh/pull/6621

**Comment by denelon** [comment]
It's hackathon week here at Microsoft in our organization. @AmelBawa-msft just did a demo where he ran `winget configure light.winget` and `winget configure dark.winget` and they both succeed using DSCv3 with his hackathon version of Windows Terminal apply the theme changes to Windows Terminal!!!

It's also an internal build of WinGet (1.11.180-preview). I think we're close to pushing that preview (or a newer one) out.

We will likely have lots of feedback for documentation, and some learning curve pain to share and improve on.

**Comment by mdanish-kh** [comment]
[WinGet-Create](https://github.com/microsoft/winget-create/blob/main/doc/dsc.md) added support for DSCv3 to manage user settings. One can now install the latest version of winget-create, run `winget configure export --all -o config.winget` and see the relevant settings pulled out


```yaml
- name: Microsoft.WinGetCreate/Settings-0
  type: Microsoft.WinGetCreate/Settings
  dependsOn:
  - winget_Microsoft.WingetCreate
  properties:
    settings:
      Telemetry:
        disable: false
      Manifest:
        format: "yaml"
      WindowsPackageManagerRepository:
        name: "winget-pkgs"
        owner: "microsoft"
      CleanUp:
        disable: false
        intervalInDays: 7
      $schema: "https://aka.ms/wingetcreate-settings.schema.0.1.json"
      Visual:
        anonymizePaths: true
```
