### DISCUSSION TITLE
Microsoft.DSC/Group dependsOn with Microsoft.DSC/Assertion

### DISCUSSION THREAD

**Discussion by csoto-dish** [PowerShell/DSC#725] [Q&A] [answered]
Hi team,

I am attempting to build a yaml config file for DSCv3 that uses a bit of logic with Assertion to determine what configuration to run. I have these configurations set up as Groups with a dependsOn to an Assertion with a nested OSInfo version check. Here is an example:
```yaml
resources:
  - name: Schannel Protocols 2025
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: TLS 1.3\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.3\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server
          valueName: Enabled
          valueData:
            DWord: 1
    dependsOn:
    - "[resourceId('Microsoft.DSC/Assertion','Server 2025 check')]"
  - name: Server 2025 check
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Server 2025
        type: Microsoft/OSInfo
        properties:
          version: "10.0.26100"
```

The Assertion seems to work, however configurations for other Groups in the same yaml file with a dependsOn for their corresponding OS versions are getting applied in order even if their Assertion fails. This is all very new to me, so perhaps I am doing something wrong. Hoping someone can offer some guidance.

Thanks

**Comment by Gijsreyn** [comment]
Can you perhaps paste in the full YAML that you have and put the expected outcomes for each group / server your applying it to as such:

```yaml
name: Schannel Protocols 2025
type: Microsoft.DSC/Group
properties:
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
   # Resources here
```

**Reply by csoto-dish** [reply]
Sure thing

```
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
  - name: Windows Baseline
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Ciphers
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers
          _exist: false
      - name: CipherSuites
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CipherSuites
          _exist: false
      - name: Hashes
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes
          _exist: false
      - name: KeyExchangeAlgorithms
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms
          _exist: false
      - name: Multi-Protocol Unified Hello\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: Multi-Protocol Unified Hello\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: PCT 1.0\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: PCT 1.0\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: SSL 2.0\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: SSL 2.0\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: SSL 3.0\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: SSL 3.0\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.0\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.0\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.2\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.2\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
          valueName: Enabled
          valueData:
            DWord: 1
      - name: Cipher Suite
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002
          valueName: Functions
          valueData:
            String: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256
  - name: Schannel Protocols 2025
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: TLS 1.1\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.1\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.3\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.3\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server
          valueName: Enabled
          valueData:
            DWord: 1
    dependsOn:
    - "[resourceId('Microsoft.DSC/Assertion','Server 2025 check')]"
  - name: Schannel Protocols 2022
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: TLS 1.1\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.1\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.3\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.3\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server
          valueName: Enabled
          valueData:
            DWord: 1
    dependsOn:
    - "[resourceId('Microsoft.DSC/Assertion','Server 2022 check')]"
  - name: Schannel Protocols 2019
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: TLS 1.1\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.1\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
          valueName: Enabled
          valueData:
            DWord: 0
      - name: TLS 1.3\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3
          _exist: false
    dependsOn:
    - "[resourceId('Microsoft.DSC/Assertion','Server 2019 check')]"
  - name: Schannel Protocols 2016
    type: Microsoft.DSC/Group
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: TLS 1.1\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.1\Server
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
          valueName: Enabled
          valueData:
            DWord: 1
      - name: TLS 1.3\Client
        type: Microsoft.Windows/Registry
        properties:
          keyPath: HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3
          _exist: false
    dependsOn:
    - "[resourceId('Microsoft.DSC/Assertion','Server 2016 check')]"
  - name: Server 2025 check
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Server 2025
        type: Microsoft/OSInfo
        properties:
          version: "10.0.26100"
  - name: Server 2022 check
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Server 2022
        type: Microsoft/OSInfo
        properties:
          version: "10.0.20348"
  - name: Server 2019 check
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Server 2019
        type: Microsoft/OSInfo
        properties:
          version: "10.0.17763"
  - name: Server 2016 check
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
      - name: Server 2016
        type: Microsoft/OSInfo
        properties: version: "10.0.14393"
```
          

What I am expecting: As it processes each group in the config, it should run the corresponding Assertion check and if false, skip applying to configuration (or apply if it is true). In this case making changes to the registry if the OSInfo version is a match.

What is happening: All configs in every group are applied, regardless of the success/fail of the Assertion.

**Reply by Gijsreyn** [reply]
I would agree with the explanation that was given. I just tried the example in the repository:

```yaml
# Example configuration that uses assertions to validate the environment before running the configuration.
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: current user registry
  type: Microsoft.Windows/Registry
  properties:
    keyPath: HKCU\1\2\3
    _exist: true
  dependsOn:
  - "[resourceId('Microsoft.DSC/Assertion','my assertions')]"
- name: my assertions
  type: Microsoft.DSC/Assertion
  properties:
    $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
    resources:
    - name: os
      type: Microsoft/OSInfo
      properties:
        family: Windows
    - name: system root
      type: Microsoft.Windows/Registry
      properties:
        keyPath: HKLM\Software\Microsoft\Windows NT\CurrentVersion
        valueName: SystemRoot
        valueData:
          # this is deliberately set to z: drive so that the assertion fails
          String: Z:\Windows
```

This one doesn't work either. @SteveL-MSFT or @michaeltlombardi , is something missing here?
