### DISCUSSION TITLE
Retrieve SID of user using configuration document (add more example on how to use variables in the documentation)

### DISCUSSION THREAD

**Discussion by dummys** [PowerShell/DSC#754] [Q&A]
To modify some registry key value, I need to retrieve the SID of the user. in DSC 2.0 I do like this:
```powershell
    $mysid = (New-Object System.Security.Principal.NTAccount($myusername)).Translate([System.Security.Principal.SecurityIdentifier]).value
```
And then I use `${mysid}`
I tried to do the same on DSC 3.0 but I was not able to execute powershell code within my yaml configuration document.
Unfortunately the documentation on using variables in not good because it didnt' exist any examples, even copilot is not giving good result.I was able find documentation on parameters, thus I tried to do the same with variables: https://learn.microsoft.com/en-gb/powershell/dsc/reference/schemas/config/functions/parameters?view=dsc-3.0
I tried a lot of things without make it work like:
```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
variables:
  siduser: mysidoftheuser
resources:
    - name: DisableLoginBackgroundImageonLockScreen
      type: Microsoft.Windows/Registry
      properties:
         _exist: true
        keyPath: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\SystemProtectedUserData\[variables('siduser')]\AnyoneRead\LockScreen
        valueName: HideLogonBackgroundImage
        valueData:
          DWord: 1
```

**Comment by Gijsreyn** [comment]
@dummys I tried to follow what you're attempting to achieve. Even thought I like variables and parameters, might the following example by Mikey in the repository solve your case: https://github.com/PowerShell/DSC/blob/9fc9a807c72b4e49901d9ec8188ab4dcafebf55d/dsc/examples/winps_script.dsc.yaml

**Comment by dummys** [comment]
hi,
still struggling on how I can retrieve and store the value in a variable:

```powershell
# yaml-language-server: $schema=https://aka.ms/dsc/schemas/v3/bundled/config/document.vscode.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
metadata:
  Microsoft.DSC:
    securityContext: elevated
variables:
  svcnumber: "temp"
resources:
  - type: Microsoft.Windows/WindowsPowerShell
    name: Get the number for user services using old powershell
    properties: 
      resources:
        - name: Get the number of user for user services
          type: PSDesiredStateConfiguration/Script
          properties:
            GetScript: |
              $svcname = $(Get-Service | Where-Object {$_.Name -like 'WpnUs*'}).Name
              $text = $svcname -split "_"
              $using:svcnumber = $text[1]
              # Returning result must be this type of hashtable
              @{Result=$text[1]}
            TestScript: |
              # TestScript must return a boolean
              $true
            SetScript: |
              $svcname = $(Get-Service | Where-Object {$_.Name -like 'WpnUs*'}).Name
              $text = $svcname -split "_"
                            # Returning result must be this type of hashtable
              @{Result=$text[1]}
```
But I get the following error:
```
+ $using:svcnumber = $text[1]
+ ~~~~~~~~~~~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept assignments, such as a variable or a property."
2025-04-16T15:46:02.859446Z ERROR Command: Resource 'powershell' [exit code 1] manifest description: Error
```

**Reply by Gijsreyn** [reply]
I don't think using: statements will work like that to pass it along. I was trying something like this:

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
  - name: Get the number of user for user services
    type: PSDesiredStateConfiguration/Script
    properties:
      GetScript: |
        $string = 'MyString'
        [System.Environment]::SetEnvironmentVariable('stringValue',$string, 'Machine')

        $env:stringValue = $string

        @{Result=$string}
      TestScript: |
        # TestScript must return a boolean
        $true
      SetScript: |
        # SetScript must return a boolean
        $true
  - name: Echo variable
    type: Microsoft.DSC.Debug/Echo
    properties:
      output: "[envvar('stringValue')]"
    dependsOn:
    - "[resourceId('PSDesiredStateConfiguration/Script', 'Get the number of user for user services')]"
```

However, when the environment variable is set, it doesn't pick it up during the _current session_. Only if you restart your session in PowerShell does it work. Thinking of other ways to get around this...
