### DISCUSSION TITLE
Is it possible to forward parameters to includes?

### DISCUSSION THREAD

**Discussion by gtbuchanan** [PowerShell/DSC#895] [Q&A]
[This](https://github.com/PowerShell/DSC/blob/main/dsc/examples/include.dsc.yaml#L9) example shows `parametersFile` being passed to the `Microsoft.DSC/Include` resource. However, I'm wondering if it's supported to do something like this instead:

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
parameters:
  myParam:
    type: string
    defaultValue: "test"
resources:
  - name: Echo
    type: Microsoft.DSC.Debug/Echo
    properties:
      output: "[parameters('myParam')]"
  - name: Include
    type: Microsoft.DSC/Include
    properties:
      configurationFile: other.dsc.yaml
      parameters:
        myParam: "[parameters('myParam')]"
```

I'm trying to author a composite configuration where I can pass a single parameters file to simplify usage. Specifying an inner `parametersFile` would prevent me from being able to use a single composite configuration (AFAIK).
