### ISSUE TITLE
Registry meta-resource

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#102]
### Summary of the new feature / enhancement

There may be a large set of applications on Windows that store their configuration in the registry.  It may make sense to have the `registry` resource accept a file that maps registry locations to a resource definition.

### Proposed technical implementation details (optional)

For example, PS7 uses two registry values to control Microsoft Update:

HKLM\Software\Microsoft\PowerShellCore\UseMU = 1
HKLM\Software\Microsoft\PowerShellCore\InstalledVersions\39243d76-adaf-42b1-94fb-16ecf83237c8\Install = 1

The first enables updating via MU and the second installs if not installed (update doesn't do anything if not installed).

The `registry` resource could have parameters like `registry -resourceFile ps7.json` which contains:

```json
{
  "name": "PowerShellMicrosoftUpdate",
  "version": "1.0.0",
  "properties": {
    "automaticUpdates": {
        "key": "HKLM\Software\Microsoft\PowerShellCore",
        "name": "UseMU",
        "valueType": "DWORD",
        "values": [ 0, 1 ]
    },
    "automaticInstall": {
        "key": "HKLM\Software\Microsoft\PowerShellCore\InstalledVersions\39243d76-adaf-42b1-94fb-16ecf83237c8",
        "name": "Install",
        "valueType": "DWORD",
        "values": [ 0, 1 ]
    }
  }
}
```

This is hypothetical and the `values` property needs to be thought out on how to properly support this.  Also, for the `registry` resource to synthesize a DSC resource, it would need to generate JSON schema or implement the `validate` subcommand and perform its own validation against the incoming JSON (this seems more feasible).

Each synthetic resource would need it's own resource manifest that uses the `registry` resource.
In this example, imagine a `microsoft.powershell.microsoftupdate.dsc.json` file in a location either the `registry` resource
is aware of or in the same location as `registry.exe`:

```json
{
  "manifestVersion": "1.0",
  "type": "Microsoft.PowerShell/MicrosoftUpdate",
  "version": "0.1.0",
  "get": {
    "executable": "registry",
    "args": [
      "get",
      "--resourceFile",
      "microsoft.powershell.microsoftupdate.json"
    ],
    "input": "stdin"
  },
  "set": {
    "executable": "registry",
    "args": [
      "set",
      "--resourceFile",
      "microsoft.powershell.microsoftupdate.json"
    ],
    "input": "stdin"
  },
  "test": {
    "executable": "registry",
    "args": [
      "test",
      "--resourceFile",
      "microsoft.powershell.microsoftupdate.json"
    ],
    "input": "stdin"
  },
  "validate": {
    "executable": "registry",
    "args": [
      "validate",
      "--resourceFile",
      "microsoft.powershell.microsoftupdate.json"
    ],
    "input": "stdin"
  },
  "exitCodes": {
    "0": "Success",
    "1": "Invalid parameter",
    "2": "Invalid input",
    "3": "Registry error",
    "4": "JSON serialization failed"
  }
}
```

**Comment by SteveL-MSFT** [comment]
We should consider a section in the resource manifest as `resourceData` that can be passed to the resource itself (or perhaps we call it a different type of resource) that uses the data to synthesize a resource.  This would be useful not just for registry, but also things like WMI where you want to transform the raw object into something more tailored for configuration.  In the registry case, it makes sense to support an enum instead of having the user specify and remember what `0` or `1` means.  Also may be useful to validate ranges, max length for strings, etc...

**Comment by denelon** [comment]
I've encountered several configurations with multiple instances of resources attempting to modify the registry. I can see this as a very common scenario. For Windows Settings this is a common pattern until we complete the v3 implementation of a Windows Settings resource. Even after that, it's fairly common to want to modify registry keys.

**Comment by SteveL-MSFT** [comment]
Thinking about this further, I think this can be simply implemented as an adapter and adapted resource.

The current registry resource would have an adapter mode (this can simply be a command line arg) where all it needs is the mapping of the property name to the registry value as an array.  The adapted resource manifest can be augmented to allow for `adaptedContent` instead of `path` (one, but not both needs to be provided) so that can eliminate the need for an additional file.  The resource author using this is responsible for authoring the JSON schema which would provide limits to the values (type, enumeration, regex, etc...).

This model can also be used with WMI.

**Comment by SteveL-MSFT** [comment]
I have a proposal best explained by an example I'm building:

```yaml
# Adapted Registry resource for personalization settings defined in:
# https://learn.microsoft.com/en-us/windows/apps/develop/settings/settings-common#personalization---colors

$schema: https://aka.ms/dsc/schemas/v3/bundled/adaptedresource/manifest.json
type: Microsoft.Windows/Personalization
kind: resource
version: 1.0.0
capabilities:
- get
- set
description: Controls Windows personalization settings such as accent color, light/dark mode, and transparency effects.
author: Microsoft Corporation
requireAdapter: Microsoft.Windows.Adapter/Registry
content:
  appUsesLightTheme:
    keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    valueType: REG_DWORD
    valueName: AppUseLightTheme
    map:
      false: 0
      true: 1
  systemUsesLightTheme:
    keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    valueType: REG_DWORD
    valueName: SystemUsesLightTheme
    map:
      false: 0
      true: 1
  colorPrevalence:
    keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    valueType: REG_DWORD
    valueName: ColorPrevalence
    map:
      false: 0
      true: 1
  transparencyEffects:
    keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    valueType: REG_DWORD
    valueName: EnableTransparency
    map:
      false: 0
      true: 1
  startMenuVisiblePlaces:
    keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Start
    valueType: REG_BINARY
    valueName: VisiblePlaces
    map:
      # Documents: {2D34D5CE-FA5A-4543-82F2-22E6EAF7773C}
      Documents: [0xCE, 0xD5, 0x34, 0x2D, 0x5A, 0xFA, 0x43, 0x45, 0x82, 0xF2, 0x22, 0xE6, 0xEA, 0xF7, 0x77, 0x3C]
      # Downloads: {E367B32F-89DE-4355-BFCE-61F37B18A937}
      Downloads: [0x2F, 0xB3, 0x67, 0xE3, 0xDE, 0x89, 0x55, 0x43, 0xBF, 0xCE, 0x61, 0xF3, 0x7B, 0x18, 0xA9, 0x37]
      # Music: {B00B0620-7F51-4C32-AA1E-34CC547F7315}
      Music: [0x20, 0x06, 0x0B, 0xB0, 0x51, 0x7F, 0x32, 0x4C, 0xAA, 0x1E, 0x34, 0xCC, 0x54, 0x7F, 0x73, 0x15]
      # Pictures: {383F07A0-E80A-4C80-B05A-86DB845DBC4D}
      Pictures: [0xA0, 0x07, 0x3F, 0x38, 0x0A, 0xE8, 0x80, 0x4C, 0xB0, 0x5A, 0x86, 0xDB, 0x84, 0x5D, 0xBC, 0x4D]
      # Videos: {42B3A5C5-7D86-42F4-80A4-93FACA7A88B5}
      Videos: [0xC5, 0xA5, 0xB3, 0x42, 0x86, 0x7D, 0xF4, 0x42, 0x80, 0xA4, 0x93, 0xFA, 0xCA, 0x7A, 0x88, 0xB5]
      # Network: {FE758144-080D-42AE-8BDA-34ED97B66394}
      Network: [0x44, 0x81, 0x75, 0xFE, 0x0D, 0x08, 0xAE, 0x42, 0x8B, 0xDA, 0x34, 0xED, 0x97, 0xB6, 0x63, 0x94]
      # UserProfile: {74BDB04A-F94A-4F68-8BD6-4398071DA8BC}
      UserProfile: [0x4A, 0xB0, 0xBD, 0x74, 0x4A, 0xF9, 0x68, 0x4F, 0x8B, 0xD6, 0x43, 0x98, 0x07, 0x1D, 0xA8, 0xBC]
      # Explorer: {148A24BC-D60C-4289-A080-6ED9BBA24882}
      Explorer: [0xBC, 0x24, 0x8A, 0x14, 0x0C, 0xD6, 0x89, 0x42, 0xA0, 0x80, 0x6E, 0xD9, 0xBB, 0xA2, 0x48, 0x82]
      # Settings: {52730886-51AA-4243-9F7B-2776584659D4}
      Settings: [0x86, 0x88, 0x73, 0x52, 0xAA, 0x51, 0x43, 0x42, 0x9F, 0x7B, 0x27, 0x76, 0x58, 0x46, 0x59, 0xD4]
    startMenuShowRecentList:
      keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Start
      valueType: REG_BOOL
      valueName: ShowRecentList
      map:
        false: false
        true: true
    showRecommendedApps:
      keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      valueType: REG_BOOL
      valueName: Start_TrackDocs
      map:
        false: false
        true: true
    taskbarShowBadges:
      keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarBadges
      valueType: REG_SZ
      valueName: SystemSettings_Taskbar_Badging
      map:
        false: '0'
        true: '1'
    desktopTaskbarShowBadges:
      keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarBadges
      valueType: REG_SZ
      valueName: SystemSettings_DesktopTaskbar_Badging
      map:
        false: '0'
        true: '1'
    multimonitorTaskbarGroupingMode:
      keyPath: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\MMTaskbarGlomLevel
      valueType: REG_SZ
      valueName: SystemSettings_DesktopTaskbar_GroupingMode
      map:
        # Always combine, hide labels: 0
        AlwaysCombineHideLabels: 0
        # Combine when taskbar is full: 1
        CombineWhenTaskbarIsFull: 1
        # Never combine: 2
        NeverCombine: 2
schema:
  embedded:
    $schema: http://json-schema.org/draft-07/schema#
    $id: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/resources/Adapted/Three/v0.1.0/schema.json
    title: Microsoft.Windows/Personalization
    description: Windows personalization settings such as accent color, light/dark mode, and transparency effects.
    type: object
    required: []
    additionalProperties: false
    properties:
      appUsesLightTheme:
        type: boolean
        title: App Uses Light Theme
        description: Indicates whether the app uses the light theme.
      systemUsesLightTheme:
        type: boolean
        title: System Uses Light Theme
        description: Indicates whether the system uses the light theme.
      colorPrevalence:
        type: boolean
        title: Color Prevalence
        description: Indicates whether the accent color is applied to Start, taskbar, and action center
      transparencyEffects:
        type: boolean
        title: Transparency Effects
        description: Indicates whether transparency effects are enabled.
      startMenuVisiblePlaces:
        type: array
        title: Start Menu Visible Places
        description: A list of places that are visible in the Start menu.
        items:
          type: string
          enum:
            - Documents
            - Downloads
            - Music
            - Pictures
            - Videos
            - Network
            - UserProfile
            - Explorer
            - Settings
      startMenuShowRecentList:
        type: boolean
        title: Start Menu Show Recent List
        description: Specifies whether apps that were recently installed in Start in various surfaces are shown on Start.
      showRecommendedApps:
        type: boolean
        title: Show Recommended Apps
        description: Specifies whether recommended files in Start, recent files in File Explorer, and items in Jump Lists are shown.
      taskbarShowBadges:
        type: boolean
        title: Taskbar Show Badges
        description: Specifies whether badges on taskbar buttons are shown.
      desktopTaskbarShowBadges:
        type: boolean
        title: Desktop Taskbar Show Badges
        description: Specifies whether badges on taskbar buttons are shown on the desktop.
      multimonitorTaskbarGroupingMode:
        type: string
        title: Multimonitor Taskbar Grouping Mode
        description: Specifies how taskbar buttons are grouped on multiple displays.
        enum:
          - AlwaysCombineHideLabels
          - CombineWhenTaskbarIsFull
          - NeverCombine
```
