### ISSUE TITLE
ResourceManifest::Get should be optional

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#166]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

With addition of `Export` functionality, that may be the only functionality that a resource implements;
however currently specifying 'Get' in the manifest is mandatory, which produces an error if resource does not support it:

```
PS C:\DSCv3> dsc resource export -r Microsoft/ProcessList
Error: Manifest: C:\DSCv3\bin\debug\process.dsc.resource.json
JSON: missing field `get` at line 9 column 1
```

### Expected behavior

```console
NA
```

### Actual behavior

```console
NA
```

### Environment data

```PowerShell
NA
```

### Version

v1

**Comment by michaeltlombardi** [comment]
Should `get` be optional, or should the manifest have a property like `export` that validates against a subschema like:

```yaml
title:       Resource Exporting
description: |
  Defines whether the resource can be used to export instances. When this value is `true`,
  the resource is processed normally with the `dsc resource export` and `dsc config export`
  commands. When this value is `false`, the resource is ignored. When this value is `only`,
  the resource is invalid for other operations, like `get` and `set`.
type:    [boolean, string]
enum:    [true, false, only]
default: false
```

And then an export-only manifest would define as either:

1. Top-level keyword:
   
   ```jsonc
   {
     "export": "only",
     "get": {
       // get definition
     }
   }
   ```
   
1. Keyword in `get`:

   ```jsonc
   {
     "get": {
       "export": "only",
       // get definition
     }
   }
   ```

Are there times where we would expect the `export` to be something different from `get`, except for whether instance properties are passed to the resource? Do I have to define `export` and `get` fully to support both, or can I do something like this?

```jsonc
{
  "get": {
    // get definition
  },
  "export": true
}
```

Instead of:

```jsonc
{
  "get": {
    // get definition
  },
  "export": {
    // same as get definition
  }
}
```
