### ISSUE TITLE
Reject unknown parameters

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DSC#200]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

'{"foo": "bar"}' | dsc resource get --resource testresource/name

### Expected behavior

```console
'{"foo": "bar"}' | dsc resource get --resource testresource/name
ERROR: 'foo' is not defined as a valid parameter for resource 'testresource/name'
```

### Actual behavior

```console
'{"foo": "bar"}' | dsc resource get --resource testresource/name
actualState:
  (output from test resource)
```

### Environment data

```PowerShell
0.2
```

### Version

0.2

**Comment by michaeltlombardi** [comment]
The JSON validation should depend on the [instance schema][01] the resource manifest defines. In JSON Schema, there are two relevant keywords that affect whether unknown properties are valid: [`additionalProperties`][02] and [`unevaluatedProperties`][03]. There's also [`patternProperties`][04], where properties with matching names are validated by a specified subschema.

By default, unknown properties of an object are considered valid. Only when either `additionalProperties` or `unevaluatedProperties` is set to `false`, are unknown properties considered invalid.

We should strongly recommend that resource authors define one of those keywords (`unevaluatedProperties` is preferred, as it doesn't affect extensibility whereas `additionalProperties` prevents it) for their resource instance schemas.

Using a couple snippet examples (YAML bc I don't love writing JSON by hand):

<details open><summary>Unknown properties are allowed (default)</summary>

```yaml
schema:
  embedded:
    $schema:  https://json-schema.org/draft/2020-12/schema
    type:     object
    required: [scope]
    properties:
      scope:
        enum: [machine, user]
```

</details>

<details open><summary>Unknown properties are allowed (explicit)</summary>

```yaml
schema:
  embedded:
    $schema:  https://json-schema.org/draft/2020-12/schema
    type:     object
    required: [scope]
    unevaluatedProperties: true
    properties:
      scope:
        enum: [machine, user]
```

</details>

<details open><summary>Unknown properties are forbidden</summary>

```yaml
schema:
  embedded:
    $schema:  https://json-schema.org/draft/2020-12/schema
    type:     object
    required: [scope]
    unevaluatedProperties: false
    properties:
      scope:
        enum: [machine, user]
```

</details>

<details open><summary>Unknown properties are allowed, but must be strings</summary>

```yaml
schema:
  embedded:
    $schema:  https://json-schema.org/draft/2020-12/schema
    type:     object
    required: [scope]
    unevaluatedProperties:
      type: string
    properties:
      scope:
        enum: [machine, user]
```

</details>

[01]: https://learn.microsoft.com/en-us/powershell/dsc/reference/schemas/resource/manifest/schema/property?view=dsc-3.0
[02]: https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties
[03]: https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties
[04]: https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties
