### ISSUE TITLE
Proposed additional well-known properties

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DSC#201]
### Summary of the new feature / enhancement

Suggesting the following for discussion and consideration. This is based on a review of 2500 resources currently available in the PowerShell Gallery. The motivation to include items from this list (some or all) is to standardize across resources so that users have a consistent experience across resources from many authors. Of course, anyone can choose to drop the underscore and re-implement for any reason.

Additional considerations for discussion that feel a bit more like they would have specific implementation requirements so might not be suitable?
"Server"
"Database"
"State"

Finally, it might be worth discussing if it would be possible to standardize a password parameter to lead authors towards best practices for security. Referencing a secure password service rather than storing the string in a file, for example.
"Password"

### Proposed technical implementation details (optional)

**_name**
```yaml
title: Name
description: >-
  Indicates a short string that provides a name for the instance.
type: string
```

**_description**
```yaml
title: Description
description: >-
  Indicates a long string that provides details about the instance.
type: string
```

**_version**
```yaml
title: Version
description: >-
  Indicates a version number for the instance. Semantic version format is preferred but not required.
type: string
```

**_path**
```yaml
title: File System Path
description: >-
  Indicates the path to a file or folder represented in DOS, UNC, or Files System Hierarchy format. Should not be used for Internet locations.
type: string
```

**_url**
```yaml
title: Uniform Resource Locator
description: >-
  Indicates a reference to a specific Internet resource using format protocol://nameorip:port/path. Offen used when referencing untrusted content. A URI path is also acceptable.
type: string
```

**_version**
```yaml
title: Version
description: >-
  Indicates a version number for the instance. Semantic version format is preferred but not required.
type: string
```
