### ISSUE TITLE
dsc get fails when using powershellgroup resources

### ISSUE THREAD

**Issue by jchancellor-ms** [PowerShell/DSC#260]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Based on powershell sample here - (https://learn.microsoft.com/en-us/powershell/dsc/reference/psdscresources/resources/windowsfeature/example?view=dsc-2.0) - Invoke-DSCResource 's get method only accepts a subset of the properties and isn't smart enough to throw the unnecessary items away.  

This results in errors similar to the following: "Get-TargetResource: A parameter cannot be found that matches parameter name 'Ensure'" when running dsc get.  

I was able to work around this temporarily by adding the following code to the powershellgroup.resource.ps1 file after line 165. However, a more formal fix should probably be reviewed to determine if things like Credentials need to be retained and how to get them for each resource type.

`            $nonGetProperties = ((Get-DscResource -Name $ResourceTypeName -Module $ModuleName).Properties | where {$_.IsMandatory -eq $false}).Name
            foreach ($property in $nonGetProperties){
                $inputht.remove($property)
            }`

My config yaml file is as follows:

```yaml
# example.dsc.config.yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
resources:
  - name: powershell-dsc-resources
    type: DSC/PowerShellGroup
    properties:
      resources:
      - name: DNS 
        type: PSDscResources/MSFT_WindowsFeature
        properties:
          Name: DNS
          Ensure: Present`
```

### Expected behavior

```console
dsc get should complete discovery of the resource
```

### Actual behavior

```console
Error: "Get-TargetResource: A parameter cannot be found that matches parameter name 'Ensure'"
```

### Error details

```console
"Get-TargetResource: A parameter cannot be found that matches parameter name 'Ensure'"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

7.3.9
