### ISSUE TITLE
The `int()` function incorrectly handles non-integer numbers

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#390]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When using the `int()` function, I expect it to return the same value for a fractional number as the string representation of that fractional number. However, instead of returning `4` for `4.7`, it returns `7`.

### Expected behavior

```powershell
@'
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/10/config/document.json
resources:
- name: Echo integer value
  type: Test/Echo
  properties:
    output:
      fromString: "[int('4.7')]"
      fromNumber: "[int(4.7)]"
'@ | dsc config get
```
```yaml
results:
- name: Echo integer value
  type: Test/Echo
  result:
    actualState:
      output:
        fromString: 4
        fromNumber: 4
messages: []
hadErrors: false
```

### Actual behavior

```powershell
@'
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/10/config/document.json
resources:
- name: Echo integer value
  type: Test/Echo
  properties:
    output:
      fromString: "[int('4.7')]"
      fromNumber: "[int(4.7)]"
'@ | dsc config get
```
```yaml
results:
- name: Echo integer value
  type: Test/Echo
  result:
    actualState:
      output:
        fromString: 4
        fromNumber: 7
messages: []
hadErrors: false
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

Latest build from `main`
