### ISSUE TITLE
Handle Restart Dependencies

### ISSUE THREAD

**Issue by tgauth** [PowerShell/DSC#451]
### Summary of the new feature / enhancement

 Relating to #50, as a user I want to know any dependencies of my process/service that needs restarting so that I'm fully aware of the impacts/overhead of restarting.

**Comment by SteveL-MSFT** [comment]
From the meeting, I think two different aspects should be covered:

- dependents that are affected
- other things that need to be restarted for configuration to take effect

Perhaps we can have two additional optional top level properties to `_restartRequired`:
 
```yaml
_restartRequired:
  service:
    name: sshd
    id: 1234
  dependentsAffected:
    service:
      name: foo
      id: 1234
    process:
      name: bar
      id: 1234
  restartRequired:
    service:
      name: hello
    process:
      name: world  
```

Where both are arrays.  Still would need a real world scenario for `restartRequired` that would not include dependents that auto-restart if the top service/process is restarted.
