### ISSUE TITLE
Allow resources to return metadata

### ISSUE THREAD

**Issue by tgauth** [PowerShell/DSC#467]
### Summary of the new feature / enhancement

Permit resources to return metadata like `_messages` to provide human-readable context for `WhatIf` executions

### Proposed technical implementation details (optional)

Sample output:

``` yaml
results:
- metadata:
    Microsoft.DSC:
      duration:
      _messages: key HKCU\1\2\3 with name Hello and data World does not exist; would create keys 1, 2, and 3
- name: foo
  type: Microsoft.Windows/Registry
  result:
    beforeState:
      keyPath: HKCU\1\2\3
      _exist: false
    afterState:
      keyPath: HKCU\1\2\3
      valueName: hello
      valueData: world
```
