### ISSUE TITLE
WMI Adapter updates

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#475]
### Summary of the new feature / enhancement

Support:

- set
- export
- delete
- method invocation

### Proposed technical implementation details (optional)

Many WMI classes support methods.  We should maybe just have a `WMIMethodInvocation` metaclass that takes the namespace, class, method name, and a property bag (key/value pairs) that would be the inputs to the method.  The only problem with this approach is that the user needs to know all that info.

Alternatively, but would be noisy when listing, is to have dynamic instances returned that represent each method that can be called.

**Comment by SteveL-MSFT** [comment]
WMI Adapter should use a WMI query if there are properties specified:

```yaml
type: root.cimv2/Win32_OperatingSyste
properties:
  caption:
  version:
  osarchitecture:
  oslanguage:
```

This should be turned in to `select caption, version, osarchitecture, oslanguage from win32_operatingsystem`
