### ISSUE TITLE
Large output not returned

### ISSUE THREAD

**Issue by Gijsreyn** [PowerShell/DSC#491]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Summary

Whenever working with the export operation, output can be large. Take for example the scenario where you want to extract all the software installed on the machine using WinGet. If the result set becomes to large, the output is not returned to the console and dsc.exe keeps running. 

### Steps to reproduce

The steps are a bit difficult to reproduce, but on my workstation, I have around 270+ packages installed. When implementing the Export() functionality myself in the `Microsoft.WinGet.DSC` module, at around 230+ results set, it occured. 

1. Install Microsoft.WinGet.DSC
2. Add the following code snippet in the WinGetPackage resource

```powershell
static [WinGetPackage[]] Export() {
Assert-WinGetCommand "Get-WinGetPackage"
$resultList = [System.Collections.Generic.List[WinGetPackage]]::new()
Get-WinGetPackage | % {
  $winObj = New-Object WinGetPackage 
  $winObj.Id = $_.Id 
  $winObj.Version = $_.Version 
  
  $resultList.Add($winObj)
}
return $resultList
}
```

3. Run the following YAML snippet:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
  - name: Use class PowerShell resources
    type: Microsoft.DSC/PowerShell
    properties:
      resources:
        - name: Software
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties: {}
```

### Expected behavior

```console
Return full list of export.
```

### Actual behavior

```console
Does not return output in the console if JSON is to large.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

dsc 3.0.0-preview.8
