### ISSUE TITLE
Copy loop iteration

### ISSUE THREAD

**Issue by Gijsreyn** [PowerShell/DSC#496]
### Summary of the new feature / enhancement

As a user, I would expect you to be able to use the `copy` operation with a counter in the resource configuration document. This allows me to either drive resource configurations through the `--parameters-file` parameter or `--path` when doing an operation.

What I would expect is the following:

```yaml
# test.parameters.yaml
parameters:
  applications:
      - name: PowerShell
        id: 'Microsoft.PowerShell.Preview'

# test.config.yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
parameters:
  applications:
    type: object
resources:
  - name: Use class PowerShell resources
    type: Microsoft.DSC/PowerShell

    properties:
      copy:
        resources:
          - name: PowerShell 7 Preview
            type: Microsoft.WinGet.DSC/WinGetPackage
            properties:
              Id: "[parameters('applications.name').id]"
              Ensure: "Absent"
```

Other scenarios I'm thinking of, are the famously known DTAP street with configuration for Computer Management. 

Imagine you want to add users/groups to the relevant groups like _Adminstrator,_ or _Remote Desktop Users_. Organizations can follow naming conventions as `<groupname.<environmentName>.<regionName>', helping drive configurations from parameter files. 

You will in turn get something like:

```
# dev.group.parameters.json
parameters:
 groups:
      - name: Admin Group
        groupName: 'Administrators'
        members: ['testuser1', 'testuser2']
      - name: 'Remote Users'
        # truncated

# group.config.json
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
parameters:
  groups:
    type: object

resources:
  - name: Use class PowerShell resources
    type: Microsoft.DSC/PowerShell
    properties:
      copy:
        resources:
          - name: PowerShell 7 Preview
            type: PSDscResources/GroupSet
            properties:
              GroupName "[parameters('name').groupName]"
              Members "[parameters('name').members]"
              Ensure: "Present"
```

It's a bit short, but if you want to expand on the idea, just give me a headsup.

**Comment by SteveL-MSFT** [comment]
If I understand what you're trying to do, you want to use a resource that takes a single value and be able to specify an array so that single resource gets used for each element in the array?  Basically like a pipeline?

**Comment by Gijsreyn** [comment]
> If I understand what you're trying to do, you want to use a resource that takes a single value and be able to specify an array so that single resource gets used for each element in the array? Basically like a pipeline?

Exactly, the copying part is the key here.

**Comment by michaeltlombardi** [comment]
I think this could potentially be solved with a group resource, rather than a configuration document engine feature. Something like...

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
  - name: Use class PowerShell resources
    type: Microsoft.DSC/PowerShell
    properties:
      resoureces:
      - name: Create several groups 
        type: MyPsDscResources/Multiple:
        properties:
          ResourceType: PSDscResources/Group
          SharedDefaultProperties:
            Ensure: Present
          InstanceProperties:
          - GroupName: Group1
            Members: User1, User2
          - GroupName: Group2
            Members: User1, User3, User4
```

To use a group like this with adapted resources, you would want an adapted group - otherwise you would end up generating multiple instances of the PowerShell adapter and incur that extra overhead.

But it could work similarly for non-adapted resources:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
- name: Manage registry keys
  type: Microsoft.Dsc/MultiInstance:
  properties:
    type: Microsoft.Windows/Registry
    sharedDefaultProperties:
      _exist: true
      keyPath: HKCU\DSC\Test
    instanceProperties:
    - valueName: Foo
    - valueName: Bar
    - valueName: Baz
      valueData: { String: 'hello world' }
    - keyPath: HKCU\DSC\Test\OverrideDefault
```

**Comment by SteveL-MSFT** [comment]
The concept makes sense to me and the example from @michaeltlombardi makes sense to me to use a new Group resource.  I don't think `MultiInstance` really describes the usage, maybe `Microsoft.DSC/ForEach`?  Some naming suggestions:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
- name: Manage registry keys
  type: Microsoft.Dsc/ForEach:
  properties:
    type: Microsoft.Windows/Registry
    propertyDefaults:
      _exist: true
      keyPath: HKCU\DSC\Test
    instanceProperties:
    - valueName: Foo
    - valueName: Bar
    - valueName: Baz
      valueData: { String: 'hello world' }
    - keyPath: HKCU\DSC\Test\OverrideDefault
```
