### ISSUE TITLE
Make `Include` resource use more like a composite resource

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#585]
### Summary of the new feature / enhancement

Currently, if you `Include` a nested configuration which has parameter, it has to be passed in as a separate file.  Instead, we should allow the parameters to be passed in via the parent configuration.

### Proposed technical implementation details (optional)

Example of how this could look:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
- name: get os info
  type: Microsoft.DSC/Include
  properties:
    configurationFile: osinfo_parameters.dsc.yaml
    parameters:
      osFamily: macOS
```
