### ISSUE TITLE
DSC on Azure Pipelines Ubuntu

### ISSUE THREAD

**Issue by Gijsreyn** [PowerShell/DSC#588]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Summary

I am experiencing issues when installing `dsc.exe` on `ubuntu-latest` agent pool in Azure Pipelines. I'm running the following script:

```yaml
jobs: 
  - job: test
    displayName: 'test'
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - checkout: self 
        persistCredentials: true 
      - task: PowerShell@2
        displayName: "Run"
        inputs:
          pwsh: true
          targetType: "inline"
          script: |
            $uri = 'https://github.com/PowerShell/DSC/releases/download/v3.0.0-preview.11/DSC-3.0.0-preview.11-x86_64-unknown-linux-gnu.tar.gz'
            $filePath = '/tmp/DSC-' + '3.0.0-preview.11' + '-x86_64-unknown-linux-gnu.tar.gz'

            curl -L -o $filePath $uri
            # Create the target folder where powershell will be placed
            sudo mkdir -p /opt/microsoft/dsc

            # Expand dsc to the target folder
            sudo tar zxf $filePath -C /opt/microsoft/dsc

            # Set execute permissions
            sudo chmod +x /opt/microsoft/dsc

            # Create the symbolic link that points to dsc
            sudo ln -s /opt/microsoft/dsc /usr/bin/dsc

            # Add to path
            $env:PATH += [System.IO.Path]::PathSeparator + "/usr/bin/dsc"

            # Call version
            dsc --version 

            # Call list of resources
            dsc -l trace resource list
          ignoreLASTEXITCODE: true

```

The `dsc --version` is properly called, but when doing the resource list, I can observe:

![image](https://github.com/user-attachments/assets/8bf2d488-97aa-4143-a438-228ba67d51ca)

This hangs for an infinity time. 

### Steps to reproduce

See description

### Expected behavior

```console
Able to run `dsc resource list` on ubuntu-latest agent
```

### Actual behavior

```console
Hangs
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

dsc 3.0.0-preview.11
