### ISSUE TITLE
Allow configuration parameters to be passed as command-line parameters

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#594]
### Summary of the new feature / enhancement

Allow parameters to `dsc` after `--` to be interpreted as parameters to the configuration.

### Proposed technical implementation details (optional)

Assume a configuration that looks like:

```yaml
parameters:
  osFamily:
    type: string
    defaultValue: Windows
    allowedValues:
      - Windows
      - Linux
      - macOS
  name:
    type: string
```

Then we could allow config parameters to be passed as command-line parameters after `--`, so something like:

```sh
dsc config get -p ./foo.dsc.yaml -- --osFamily Windows --name test
```

One limitation to this experience is that JSON is case-sensitive, so the parameter names would have to be case-sensitive.  We could allow for case-insensitive and do an exact match first and then case-insensitive match if it only matches one (it would be a bad practice to have multiple parameters that differ by case, although it would be allowed).  However, parameter values are also case-sensitive, so we'd also need to perform a best match if there's an `allowedValues`.
