### ISSUE TITLE
Proposal: Extended Resources

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#611]
### Summary of the new feature / enhancement

> As a resource author, I want to be able to create and maintain a resource that extends the capabilities of another resource without duplicating that resource's implementation. For example, given a `File` resource that can create empty files, delete files, and set permissions and modes for files, I want to create a `TemplateFile` resource that handles processing a template to define the contents of a file without having to reimplement permissions, existence, etc myself, or requiring my users to define two instances in their configuration document when one instance _always_ implies the other.

Consider the following snippet of a fictional extended resource manifest:

```yaml
type: Mikey.Go/TemplateFile
extends:
  type: Microsoft.Dsc.Fs/File
  version: "(1.0,2.0)"
schema:
  # skipping $schema, type, etc for brevity
  $ref: "<json-schema-uri-for-file-resource>"
  required: [template]
  properties:
    template:
      type: string
      writeOnly: true
    variables:
      type: object
      writeOnly: true
    content:
      type: string
      readOnly: true
  ```
  
In this case, the `Mikey.Go/TemplateFile` resource has all of the configurable properties of the `Microsoft.Dsc.Fs/File` _and_ the new `template`, `variables`, and `content` properties that it defines.

From a functional perspective, given the following command:

```powershell
@'
path: /code/message.txt
_exist: true
permissions: 0755
owner: mikey
template: |-
  Hello, {{ .name }}!
variables:
  name: world
'@ | dsc resource get -r Mikey.Go/TemplateFile --file -
```

I would expect DSC to do the following:

1. Perform resource discovery to find `Mikey.Go/TemplateFile`
1. Because that resource defines itself as extending `Microsoft.Dsc.Fs/File`, look in the cache for that resource to see if it exists in the valid version range.
1. If it does, call the `get` operation for the `File` resource, holding the result temporarily. If it doesn't, error because the extended resource can't be used without it.
1. If the `get` operation was successful, call the `get` operation for the `Mikey.Go/TemplateFile` resource, holding the result temporarily.
1. Merge the result objects from both resources to return the canonical representation of the `TemplateFile` resource (which in this case includes the `content` property, but not the write-only `template` or `variables` properties, and the properties returned by the `File` resource.

Procedurally, DSC always invokes the extended resource _after_ the resource it extends, and only if the referenced resource doesn't error during discovery or invocation.

From a practical perspective, this would support defining minimal generic resources that still provide functionality on their own, like `File` or `OSInfo`, which resource authors could then layer various behaviors on top of to suit different needs.

I think this behavior would be _most_ useful for the `File` resource, where I can think of a dozen different iterations on managing file contents while still needing to set the existence and properties of the file itself - `TemplateFile`, `CopyFile`, `DownloadFile`.

Initially, I would expect extended resources only to _add_ new configurable properties, not replace processing for existing ones - but that could be a future enhancement too (though obviously adds complexity).

I haven't specced this proposal out fully but wanted to write up initial thoughts and submit them here.

**Comment by gaelcolas** [comment]
First of all, extending existing resources with more task specific resources makes sense, and [you can already do it](https://github.com/Azure/nxtools/blob/main/source/Classes/2.GCResources/01.GC_LinuxGroup.ps1#L2) to a certain extent with inheritance, depending on the language and implementation of the resource.

But what this proposal offers, is to allow you to do that outside of those concepts, creating a higher level abstraction layer of DSC resources.
`DSC Resource xyz --> Extend DSC Resource A`

While this is an interesting composition, it could be tackled at yet another level: The good old _Composite Resource_.

The purpose is a bit more complex:
`DSC Resource zzz --> contains DSC Resource A, THEN DSC Resource B`
But with it you can solve our other composition `DSC Resource xyz --> Extend DSC Resource A`.

I'd hate to have the two composition models fight each other (especially in terms of complexity, effort, documentation and so on...), and solving the first without addressing the second does not really make sense.

I'd add that extending that way a resource you don't manage/control, with one that you do and where they live in different places sounds like a bad operational practice to me (unmanaged drift).
When you do that, your resource should ship/embed the current dependency, so that compatibility and updates are a build issue, not an environment one.

**Comment by michaeltlombardi** [comment]
Thinking on this again, I think you're probably right, especially from a prioritization perspective - composite resources are more _generally_ useful and can solve similar problems as this proposal. Combined with the idea of adapters that make defining ergonomic resources over specific APIs (like the experimental registry adapter), I think we can probably close this issue.

With composite resources, you could do something like:

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/compositeResource.json
manifest:
  type: Mikey.Handlebars/TemplateFile
  version: 1.0.0
  description: >-
    Manage a file where the content is defined by a Handlebars template with
parameters:
  filepath:
    type: string
    description: The path to the file to manage
  template:
    type: string
    description: The Handlebars template to process as file content.
    writeOnly: true
  data:
    type: object
    description: >-
      The data to use when processing the Handlebars template. Every key in this
      object is available as a variable in the template.
    writeOnly: true
  _exist:
    type: boolean
    description: Whether the file should exist or not. Default is true.
    default: true
resources:
  - name: TemplateResolution
    type: Mikey.Handlebars/TemplateContent
    requireVersion: ^1
    properties:
      template: "[parameters('template')]"
      data: "[parameters('data')]"
  - name: file
    type: Microsoft.FileSystem/File
    requireVersion: ^1.2
    dependsOn:
      - "[resourceId('Mikey.Handlebars/TemplateContent', 'TemplateResolution')]"
    properties:
      path: "[parameters('filepath')]"
      content: >-
        [reference(
          resourceId('Mikey.Handlebars/TemplateContent', 'TemplateResolution')
        ).content]
      _exist: "[parameters('_exist')]"
outputs:
  filepath:
    type: string
    value: "[parameters('filepath')]"
  content:
    type: string
    value: >-
      [reference(
        resourceId('Mikey.Handlebars/TemplateContent', 'TemplateResolution')
      ).content]
  _exist:
    type: boolean
    value: "[parameters('_exist')]"
```

And for the adapter model (see #1550), you could have something like

```yaml
$schema: https://aka.ms/dsc/schemas/resource/adapted/manifest.json
type:    Mikey.Handlebars/TemplateFile
version: 1.0.0
kind:    resource
author:  Mikey Lombardi
description: >-
  Manage a file where the content is defined by a Handlebars template.
capabilities:
- get
- set
- delete
requireAdapter: Microsoft.FileSystem.File/Adapter
content:
  resolveCommand:
    executable: ./mikeybars # manifest side by side with executable
    args:
    - resolve
    - argument: --template
      mandatory: true
      valueDotPath: .template
    - argument: --data
      valueDotPath: .data
schema:
  embedded:
    $schema: https://json-schema.org/draft/2020-12/schema
    $id:     https://dsc.mikeywrites.fyi/schemas/Handlebars/TemplateFile/schema.json
    type:    object
    title:   Handlebars template file resource
    description: >-
      Manage a file where the content is defined by a Handlebars template.
    required:
      - filepath
      - template
    properties:
      template:
        type: string
        title: Template text
        description: The Handlebars template to process as file content.
      filepath:
        type: string
        title: Filepath
        description: The path to the file to manage.
      _exist:
        $ref: https://aka.ms/dsc/schemas/resource/properties/exist.json
      data:
        type: object
        title: Template data
        description: >-
          The data to use when processing the Handlebars template. Every key in this
          object is available as a variable in the template.
```

I'm retracting this proposal in favor of prioritizing development of composite resources and iterating on the design for this style of adapter.
