### ISSUE TITLE
Download resource

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#622]
### Summary of the new feature / enhancement

A resource that allows downloading file(s) from web.  Would need security aspects including authn and maybe even validating the server.  Proxy might be needed as well.

**Comment by michaeltlombardi** [comment]
Possible resource instance schema (non-exclusive)

```yaml
type: object
required: [sourceUri, targetFolder]
dependentRequired:
  clientKeyPath: [clientCertPath]
properties:
  sourceUri:
    description: The URI to download the file from.
    type: string
    format: uri
  targetDirectory:
    description: The folder to download the file to.
    type: string
    format: directoryPath
  targetFileName:
    description: >-
      The name of the file after downloading. Defaults to
      the base name of the URI on the remote server.
    type: string
  checksum:
    description: >-
      Defines the checksum algorithm and value to validate

    type: object
    minProperties: 1
    maxProperties: 1
    properties:
      sha256:

      sha512:
      # others as appropriate
  clientCertPath:
  clientKeyPath:
  headers:
  httpAgent:
  timeOut:
  _clobber:

**Comment by SteveL-MSFT** [comment]
I think initially we just need sufficient and secure capability for known scenarios and not end up with `curl` as a resource

**Comment by michaeltlombardi** [comment]
I do think that this resource is a useful example of one that could benefit from [Proposal: Extended Resources (#611)][gh-611] - especially for setting the attributes, mode, group, etc for the downloaded file, without requiring a user to specify a series of resources or fully reimplement the functionality of multiple resources in this one.

For example, I might want to download, extract, and define the permissions/group for a file:

```yaml
resources:
  - name: Get foo from archive
    type: Microsoft.Dsc/Download
    properties:
      sourceUri: https://archive.tailspintoys.com/foo.tar.gz
      targetDirectory: /opt/tools
      expand: true
      mode: 0755
      group: myGroup
```

I think the MVP for this resource does _not_ include convenience features like expanding archives or managing the file permissions/attributes/etc, only the download operation. Any improvements can be iteratively delivered (and those resources themselves don't exist yet).

[gh-611]: https://github.com/PowerShell/DSC/issues/611
