### ISSUE TITLE
Enable best effort error handling strategy

### ISSUE THREAD

**Issue by JohnMcPMS** [PowerShell/DSC#656]
### Summary of the new feature / enhancement

During a `config set` (and really most `config` subcommands), if a resource instance fails, I would like for any independent resources to continue to be set.  This best effort strategy allows for long running configurations to make progress toward their goal despite not being able to complete it.

Related, this would necessitate result output to be generated, including the results for successful, failed, and skipped resource instances.

This could also be an option added to the `config` command if it is deemed not appropriate as the default behavior.

**Comment by SteveL-MSFT** [comment]
The risk is that the resulting configuration could end up in an undetermined state.  Also, if we added a parameter like `--error-action` with `continue` as a value, you could hit situations where "resource 1" fails, and "resource 2" depends on output of "resource 1" and thus fails.

Is there any real world scenario where we might allow `metadata` to declare that a resource can fail and continue configuration execution?  This would at least be granular and declarative.

**Comment by michaeltlombardi** [comment]
Based on my experience with using configuration management tools and working on resources, I would recommend against any _default_ behavior that continues to modify the system after a resource raises a failing error.

I can see some value in opting-in for an error-continuation strategy at the top-level, but I would strongly prefer as an infrastructure maintainer to have the strategy described _in the document_. That would probably be most coherently implemented through `metadata`, maybe something like:

```yaml
resources:
- type: Ubuntu.Apt/Package
  name: Install tstoy-cli
  properties:
    name: tstoy-cli
  metadata:
    Microsoft.Dsc:
      onError: continue
- type:  TailspinToys.Cli/Settings
  name: configure tstoy-cli
  properties:
    scope: machine
    updateAutomatically: false
  dependsOn:
  - "[resourceId('Ubuntu.Apt/Package', 'Install tstoy-cli']"
- type: MyOrg.Internal.Share/Download
  name: Download foo document
  properties:
    sourceUri: /docs/foo.md
    targetDirectory: ~/docs
  metadata:
    Microsoft.Dsc:
      onError: continue
```

Given that example:

- If the `Ubuntu.Apt/Package` resource fails, the `TailspinToys.Cli/Settings` resource _is skipped_ because the install resource instance specified that the run should continue but the settings resource explicitly depends on the install.
- If the `TailspinToys.Cli/Settings` resource fails, the entire run stops.
- If the `MyOrg.Internal.Share/Download` resource fails, the run continues.

At the _very least_ any error-continuation strategy would have to pre-fail any nodes in the dependency graph that depend on a failed item - not even _call that resource_ - because an explicit dependency needs to be respected. Instead, DSC would have to write a message indicating that the dependent resources were skipped due to the failing dependency.

The failure strategy problem has what appears to me to be an exponential complexity - it doesn't just affect the state of the machine but also messaging and output. There's also numerous ways to approach the problem, with conflicting needs for different contexts.

I think that whatever gets built into the DSC engine (if any) for partially-failing configuration operations should probably be very limited. I think that this domain is better resolved by higher order tools, which can thoroughly plumb error handling through their own UX and model to suit their specific user context. For example, the needs of a developer configuring their machine are different from someone who is using DSC to configure a web-server for PCI compliance.
