### ISSUE TITLE
`config export` does not preserve incoming metadata

### ISSUE THREAD

**Issue by JohnMcPMS** [PowerShell/DSC#668]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

When passing a configuration document to `config export`, the metadata in the original document is not in the output document.

### Steps to reproduce

With this document:
```YAML
# repro.yml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: OS
    type: Microsoft/OSInfo
    properties:
      $id: https://developer.microsoft.com/json-schemas/dsc/os_info/20230303/Microsoft.Dsc.OS_Info.schema.json
```

The result of `dsc config export repro.yml` is:
```YAML
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
contentVersion: 1.0.0
resources:
- type: Microsoft/OSInfo
  name: Microsoft/OSInfo-0
  properties:
    $id: https://developer.microsoft.com/json-schemas/dsc/os_info/20230303/Microsoft.Dsc.OS_Info.schema.json
    family: Windows
    version: 10.0.23822
    edition: Windows 11 Enterprise
    bitness: '64'
    architecture: x86_64
metadata:
  Microsoft.DSC:
    version: 3.0.0
    operation: Export
    executionType: Actual
    startDatetime: 2025-03-05T09:10:15.418957600-08:00
    endDatetime: 2025-03-05T09:10:16.160492700-08:00
    duration: PT0.7415351S
    securityContext: Restricted
```

### Expected behavior

```console
Metadata properties *other* than `Microsoft.DSC` in the original document are in the resulting document.
```

### Actual behavior

```console
Only the `Microsoft.DSC` properties are in the output document.
```

### Error details

```console

```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.23822
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

3.0.0-rc.1

**Comment by JohnMcPMS** [comment]
PS nuisance issue: requiring 1 property to be present, even for export resources, is annoying.

**Comment by JohnMcPMS** [comment]
Works:
```
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: OS
    type: Microsoft/OSInfo
    properties:
      $id: https://developer.microsoft.com/json-schemas/dsc/os_info/20230303/Microsoft.Dsc.OS_Info.schema.json
```

Both get `2025-03-05T20:04:06.676538Z ERROR Schema: null is not of type "object"` when running `dsc config export -f E:\Temp\os-export.yaml`:
```
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: OS
    type: Microsoft/OSInfo
    properties:
```

```
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: OS
    type: Microsoft/OSInfo
```

**Comment by SteveL-MSFT** [comment]
Workaround for now is to provide an empty object so it's not `null`:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
  - name: OS
    type: Microsoft/OSInfo
    properties: {}
```

However, I consider this a bug.  Let me look into it to see if it's simple or complex to fix.
