### ISSUE TITLE
Inconsistent handling of `export`

### ISSUE THREAD

**Issue by JohnMcPMS** [PowerShell/DSC#678]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

`resource export` does not take input, but `config export` does pass the defined properties along to the resource's defined export command.  Being able to provide properties is quite useful for exporting a subset of the overall configurable data.

### Steps to reproduce

`resource export` does not take input:
```
> dsc resource export -h
Retrieve all resource instances

Usage: dsc.exe resource export [OPTIONS] --resource <RESOURCE>

Options:
  -r, --resource <RESOURCE>            The name of the resource to invoke
  -o, --output-format <OUTPUT_FORMAT>  The output format to use [possible values: json, pretty-json, yaml]
  -h, --help                           Print help
```

For my test resource that manages file contents, the `path` is the key.  `export` will export all of the files in a directory provided on `path`.  So for the file:
```YAML
#file-export.yml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
resources:
  - name: Files
    type: Microsoft.WinGet/TestFile
    properties:
      path: E:\Temp\export-target
```
Running `dsc config export -f file-export.yml` produces the following (with two files):
```YAML
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
contentVersion: 1.0.0
resources:
- type: Microsoft.WinGet/TestFile
  name: Microsoft.WinGet/TestFile-0
  properties:
    content: Uno
    path: E:\Temp\export-target\one.txt
- type: Microsoft.WinGet/TestFile
  name: Microsoft.WinGet/TestFile-1
  properties:
    content: Dos
    path: E:\Temp\export-target\two.txt
metadata:
  Microsoft.DSC:
    version: 3.0.0
    operation: export
    executionType: actual
    startDatetime: 2025-03-06T11:56:24.001246500-08:00
    endDatetime: 2025-03-06T11:56:24.596743200-08:00
    duration: PT0.5954967S
    securityContext: restricted
```

### Expected behavior

```console
`resource export` accepts input and passes it to the resource just like many of the other resource commands.
```

### Actual behavior

```console
It does not accept input.
```

### Error details

```console

```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.23823
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

3.0.0
