### ISSUE TITLE
registry.exe does not allow for empty valueName

### ISSUE THREAD

**Issue by Gijsreyn** [PowerShell/DSC#683]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

When testing out the following DSC configuration document

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Key
  type: Microsoft.Windows/Registry
  properties:
    keyPath: HKCU\1\2\3
    valueName: Key
    _exist: true
```

I was expecting a key to be created in my registry. However, the result from the `dsc config get` didn't return it. That led me to the `registry.exe`, which does not allow for only passing in a `valueName`. 

### Steps to reproduce

1. Create the following configuration document

```yaml
# example.yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Key
  type: Microsoft.Windows/Registry
  properties:
    keyPath: HKCU\1\2\3
    valueName: Key
    _exist: true
```

2, Run `dsc config set --file example.yaml`

### Expected behavior

```console
Registry key created in the expected path.
```

### Actual behavior

```console
No registry key is created.
```

### Error details

```console

```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.7
PSEdition                      Core
GitCommitId                    7.4.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

dsc 3.1.0-preview.1
