### ISSUE TITLE
Not implemented: Custom resource not supported - Managing a Windows Service

### ISSUE THREAD

**Issue by apetitjean** [PowerShell/DSC#693]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

I'm new to DSC v3 but not to DSC. I'm on Windows Server 2025, using PowerShell 7.5. I created this configuration file : 
```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json

resources:
  - name: Ensure Spooler Running
    type: PSDesiredStateConfiguration/Service
    adapter: Microsoft.Windows/WindowsPowerShell
    properties:
      Name: Spooler
      State: Running

```

I would like to configure a Windows Service to begin my learning journey of DSC v3 but I have to say, this is not a straightforward path.

Here's the command I type to test (or set) the configuration : 
`dsc config get -f C:\Scripts\DSCv3_configService.yaml`

and here's the error message I'm receiving : 
`2025-03-13T23:24:52.082168Z ERROR Not implemented: Custom resource not supported`

Am I doing something wrong or you have not yet implemented the Windows PowerShell DSC adapter?
Or maybe there's another way to do so? Could you please help me?

Thanks.

### Steps to reproduce

Here's my config :

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json

resources:
  - name: Ensure Spooler Running
    type: PSDesiredStateConfiguration/Service
    adapter: Microsoft.Windows/WindowsPowerShell
    properties:
      Name: Spooler
      State: Running
```

Here's the command I type to test (or set) the configuration : 
`dsc config get -f C:\Scripts\DSCv3_configService.yaml`

Error : `2025-03-13T23:24:52.082168Z ERROR Not implemented: Custom resource not supported`

### Expected behavior

```console
I dunno
```

### Actual behavior

```console
`2025-03-13T23:24:52.082168Z ERROR Not implemented: Custom resource not supported`
```

### Error details

```console
2025-03-13T23:24:52.082168Z ERROR Not implemented: Custom resource not supported
```

### Environment data

```PowerShell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

3.0.0
