### ISSUE TITLE
Need a common way to declare a property is sensitive

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#71]
### Summary of the new feature / enhancement

There may be a need to pass sensitive information (like an api key) to a resource that may be retrieved from AKV, for example.  DSC itself needs to know this is sensitive so it doesn't log it or emit to console and resources also need to know it's sensitive for the same reasons.

It could be as simple as a common prefix: `_sensitive` so resources can themselves decide if it's `_sensitiveString`, `_sensitiveKey`, etc...

**Comment by michaeltlombardi** [comment]
After consideration, I think the simplest way forward for this is to define and advise the use of the custom keyword `x-sensitive`. The JSON Schema maintainers wrote a [blog post][01] recommending the use of the `x-` prefix for custom annotation keywords. As this functionality is annotative - it informs the users and tools interacting with the manifest how to _handle_ the data, not how to _validate_ it - this seems like the lowest effort solution.

The updated schema for the `schema.embedded.properties` keyword in the manifest would then move from:

```yaml
title: Instance Properties
description: >-
  Defines the properties that DSC can retrieve and manage for the resource's instances.
  This keyword must define at least one property as a key-value pair. The key is the
  property's name. The value is a subschema that validates the property.
type: object
minProperties: 1
unevaluatedProperties:
  anyOf:
    - $ref: https://json-schema.org/draft/2020-12/schema
    - $ref: https://json-schema.org/draft/2019-09/schema
    - $ref: http://json-schema.org/draft-07/schema#
```

To:

```yaml
title: Instance Properties
description: >-
  Defines the properties that DSC can retrieve and manage for the resource's instances.
  This keyword must define at least one property as a key-value pair. The key is the
  property's name. The value is a subschema that validates the property.
type: object
minProperties: 1
unevaluatedProperties:
  anyOf:
    - $ref: https://json-schema.org/draft/2020-12/schema
    - $ref: https://json-schema.org/draft/2019-09/schema
    - $ref: http://json-schema.org/draft-07/schema#
  properties:
    x-sensitive:
      type:    boolean
      default: false
      title:   Value is sensitive
      description: >-
        Defines whether the property value should be handled as sensitive data. If the value is
        sensitive, like an API token, DSC and higher order tools should redact the value in any
        logs or messages. By default, property values aren't considered sensitive.
```

The Markdown documentation for this property would be:

> Defines whether the property value should be handled as sensitive data. If the value is sensitive, like an API token, DSC and higher order tools should redact the value in any logs or messages.
>
> This keyword identifies to users and tools that the value is inherently sensitive. The resource itself should also redact the value in any logs or messages. Users can still use the `sensitive` data type for a configuration parameter to force DSC to redact the data, even when it's not used for a sensitive property value.
>
> By default, property values aren't considered sensitive. To indicate that a property value is sensitive, set this keyword to `true`.
>
> In the following example, the `foo` property is sensitive but the `bar` and `baz` properties aren't.
>
> ```jsonc
> {
>     // Rest of the resource manifest...
>     "schema": {
>         "embedded": {
>             "$schema": "http://json-schema.org/draft-07/schema#",
>             "title": "SensitiveExample",
>             "type": "object",
>             "required": ["foo"],
>             "additionalProperties": false,
>             "properties": {
>                 "foo": {
>                     "type": "string",
>                     "x-sensitive": true
>                 },
>                 "bar": {
>                     "type": "string",
>                     "x-sensitive": false
>                 },
>                 "baz": { "type": "integer" }
>             }
>         }
>     }
> }
> ```

This same pattern could be used for other cases where we need to introduce annotations for DSC Resource properties, like whether a property requires elevation/root.

[01]: https://json-schema.org/understanding-json-schema/reference/annotations
