### ISSUE TITLE
Need a way to reference file paths relative to the config file

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#75]
### Summary of the new feature / enhancement

A `winget configure` scenario is that a git repo has a config.dsc.yaml which uses a resource that uses a file within the repo.  Ask is to have a built-in variable similar to `$PSScriptRoot` like `$DSCConfigRoot` that contains the path to the config file.

**Comment by SteveL-MSFT** [comment]
WG discussed this and proposes a new env var created by `dsc.exe` called `DSCConfigRoot` which contains the directory of the currently executing config file.  The PowerShell group resource (and any other language group resource) would need to know to expand this before passing to resources:

```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
resources:
- name: Use class PowerShell resources
  type: DSC/PowerShellGroup
  properties:
    resources:
    - name: foo
      type: PsDesiredStateConfiguration/MSFT_File
      properties:
        Path: $env:DSCConfigRoot/bar/baz
```
