### ISSUE TITLE
Breaking Change get --all and export return difference

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/DSC#866]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

`dsc resource get -r <type> --all` no longer has the same output compared to pre-preview7. This PR https://github.com/PowerShell/DSC/pull/861 most is most likely the cause.

### Steps to reproduce

* Run `dsc resource get -r <type> --all` on both preview7 and prior and verify all `--output-type` return correct values and yaml is returned by default to the console.

### Expected behavior

```console
Output matches versions prior to preview7

# json output
{
    "actualState": {
        "result": [
            <object>
        ]
    }
}
```

### Actual behavior

```console
Outputs json by default and if forcing to yaml does not match either.
```

### Error details

```console

```

### Environment data

```PowerShell
7.6-preview4
```

### Version

3.1-preview7

### Visuals

![Image](https://github.com/user-attachments/assets/f93c6505-93d4-4c42-ad4c-dd18a8917d18)

**Comment by ThomasNieto** [comment]
Here are the results from the current stable and the most recent preview.

@SteveL-MSFT there is a breaking change in the previews for `dsc resource get --all` and `dsc resource export` when compared to the stable version.

## get -all

### v3.0.2

```json
{
    "actualState": {
        "result": [
            {
                "Name": "PSGallery",
                "Reasons": null,
                "Ensure": 1,
                "Provider": "AnyPackage.PSResourceGet\\PSResourceGet",
                "Trusted": false,
                "Location": "https://www.powershellgallery.com/api/v2",
                "AdditionalParameters": {}
            },
            {
                "Name": "test",
                "Reasons": null,
                "Ensure": 1,
                "Provider": "AnyPackage.PSResourceGet\\PSResourceGet",
                "Trusted": true,
                "Location": "file:///c:/temp",
                "AdditionalParameters": {}
            }
        ]
    }
}
```

#### Yaml view

![Image](https://github.com/user-attachments/assets/931f3e48-0473-4a44-a276-3aa544c12003)

### 3.1.0-preview7

```json
{
    "actualState": {
        "Trusted": false,
        "Name": "PSGallery",
        "Provider": "AnyPackage.PSResourceGet\\PSResourceGet",
        "Ensure": "Present",
        "Location": "https://www.powershellgallery.com/api/v2",
        "AdditionalParameters": {},
        "Reasons": null
    }
}
{
    "actualState": {
        "Trusted": true,
        "Name": "test",
        "Provider": "AnyPackage.PSResourceGet\\PSResourceGet",
        "Ensure": "Present",
        "Location": "file:///c:/temp",
        "AdditionalParameters": {},
        "Reasons": null
    }
}
```

## Export

### v3.0.2

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
contentVersion: 1.0.0
resources:
- type: AnyPackageDsc/Source
  name: AnyPackageDsc/Source-0
  properties:
    result:
    - Trusted: false
      Reasons: null
      Provider: AnyPackage.PSResourceGet\PSResourceGet
      Location: https://www.powershellgallery.com/api/v2
      AdditionalParameters: {}
      Ensure: 1
      Name: PSGallery
    - Trusted: true
      Reasons: null
      Provider: AnyPackage.PSResourceGet\PSResourceGet
      Location: file:///c:/temp
      AdditionalParameters: {}
      Ensure: 1
      Name: test
````

### v3.1-preview7

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
contentVersion: 1.0.0
resources:
- type: AnyPackageDsc/Source
  name: AnyPackageDsc/Source-0
  properties:
    Location: https://www.powershellgallery.com/api/v2
    AdditionalParameters: {}
    Ensure: Present
    Trusted: false
    Reasons: null
    Provider: AnyPackage.PSResourceGet\PSResourceGet
    Name: PSGallery
- type: AnyPackageDsc/Source
  name: AnyPackageDsc/Source-1
  properties:
    Location: file:///c:/temp
    AdditionalParameters: {}
    Ensure: Present
    Trusted: true
    Reasons: null
    Provider: AnyPackage.PSResourceGet\PSResourceGet
    Name: test
```
