### ISSUE TITLE
Resource Schema validation ReadOnly

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/DSC#928]
### Summary of the new feature / enhancement

As a user I want `ReadOnly` properties like `_exist` and `_inDesiredState` to not be able to be passed to the resource but only allowed to be returned.

https://json-schema.org/understanding-json-schema/reference/annotations
https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-02#section-9.4

> If "readOnly" has a value of boolean true, it indicates that the
   value of the instance is managed exclusively by the owning authority,
   and attempts by an application to modify the value of this property
   are expected to be ignored or rejected by that owning authority.

The owning authority in this case is the resource.

### Proposed technical implementation details (optional)

```
type: object
properties:
  name:
    type: string
  _exist:
    type:
    - boolean
    - 'null'
    readOnly: true
  _inDesiredState:
    type:
    - boolean
    - 'null'
    readOnly: true
```
